/*
 * This source file was generated by the Gradle 'init' task
 */
package org.solver;
import org.solver.utils.Data;

public class App {

    public static void main(String[] args) {
        System.out.println(Data.getWords());
    }
}
